name: Creating Simple Web Portfolios using Github Pages
markdown: kramdown
kramdown:
  parse_block_html: true
  coderay_line_numbers: nil
pygments: true
baseurl: /github-for-portfolios
repourl: dannguyen/github-for-portfolios
safe: false
lsi: false
pygments: true
permalink: pretty
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']

disqus_shortname: danondisqus

assets:
  baseurl: /github-for-portfolios/assets
  css_compressor: sass
